import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex bg-gradient-to-br from-gray-100 to-gray-300">

        <div style={{width:'90%'}}>
          {children}  
        </div>

        <div style={{width:'10%'}}>
          <Sidebar />
        </div>

        </body>
    </html>
  );
}
